Pragma auto_vacuum;
Pragma cache_size;
Pragma case_sensitive_like;
Pragma count_changes;
Pragma database_list;
Pragma encoding;
Pragma freelist_count;
Pragma index_info;
Pragma index_list;
Pragma journal_mode;
Pragma max_page_count;
Pragma page_count;
Pragma page_size;
Pragma parser_trace;
Pragma recursive_triggers;
Pragma schema_version;
Pragma secure_delete;
Pragma sql_trace;
Pragma synchronous;
Pragma temp_store;
Pragma temp_store_directory;
Pragma user_version;
Pragma writable_schema;

PRAGMA auto_vacuum = 1;
Pragma auto_vacuum;