.header on
.mode column
.table

CREATE TABLE IF NOT EXISTS COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL
);

CREATE TABLE IF NOT EXISTS AUDIT(
    EMP_ID INT NOT NULL,
    ENTRY_DATE TEXT NOT NULL
);

CREATE TRIGGER IF NOT EXISTS audit_log AFTER INSERT 
ON COMPANY
BEGIN
   INSERT INTO AUDIT(EMP_ID, ENTRY_DATE) VALUES (new.ID, datetime('now'));
END;

INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (7, 'Paul', 32, 'California', 20000.00 );

SELECT * FROM AUDIT;

DELETE FROM COMPANY WHERE ID=7;

SELECT * FROM SQLITE_MASTER WHERE TBL_NAME='AUDIT';

DROP TRIGGER IF EXISTS AUDIT;