SELECT EMP_ID,
       NAME,
       DEPT
FROM COMPANY
INNER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID
UNION
SELECT EMP_ID,
       NAME,
       DEPT
FROM COMPANY
LEFT OUTER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID;


SELECT EMP_ID,
       NAME,
       DEPT
FROM COMPANY
INNER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID
UNION ALL
SELECT EMP_ID,
       NAME,
       DEPT
FROM COMPANY
LEFT OUTER JOIN DEPARTMENT ON COMPANY.ID = DEPARTMENT.EMP_ID;